// The two — and only two — formats the Battle tab offers.
//
// - gen9randombattle: singles, teams auto-generated by @pkmn/randoms.
// - gen9vgc2025regi:   doubles + team preview, the newest VGC format the browser
//   engine (@pkmn/sim) actually supports. (VGC 2026 Reg M-B is not in @pkmn/sim,
//   and there is no VGC team generator, so we ship legal, pre-validated sample
//   teams — validated against the real Reg I TeamValidator.)

export type FormatId = "gen9randombattle" | "gen9vgc2025regi";

export interface FormatDef {
  id: FormatId;
  label: string;
  gametype: "singles" | "doubles";
  teamPreview: boolean;
  teamSize: number; // how many are brought to the field (pick N)
  packedTeams?: string[]; // when set, teams come from here instead of the generator
}

// Legal [Gen 9] VGC 2025 Reg I teams (level 50, no restricted Pokémon).
// Verified with `new TeamValidator("gen9vgc2025regi").validateTeam(...)` → no problems.
const VGC_TEAM_A =
  "Incineroar||SafetyGoggles|Intimidate|FakeOut,KnockOff,FlareBlitz,PartingShot|Adamant|244,4,4,,20,236||||50|]" +
  "Rillaboom||AssaultVest|GrassySurge|FakeOut,GrassyGlide,WoodHammer,Uturn|Adamant|252,116,,,140,||||50|]" +
  "Flutter Mane||FocusSash|Protosynthesis|Moonblast,ShadowBall,DazzlingGleam,Protect|Timid|,,4,252,,252||||50|]" +
  "Landorus-Therian||LifeOrb|Intimidate|Earthquake,RockSlide,Uturn,Protect|Jolly|4,252,,,,252||||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Calm|236,,172,,100,||||50|]" +
  "Urshifu-Rapid-Strike||MysticWater|UnseenFist|SurgingStrikes,CloseCombat,AquaJet,Protect|Adamant|4,252,,,,252||||50|";

const VGC_TEAM_B =
  "Gholdengo||ChoiceScarf|GoodasGold|MakeItRain,ShadowBall,Thunderbolt,Trick|Timid|,,4,252,,252||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|100,252,,,156,||||50|]" +
  "Chi-Yu||ChoiceSpecs|BeadsofRuin|HeatWave,DarkPulse,Overheat,Snarl|Modest|,,4,252,,252||||50|]" +
  "Dragonite||SitrusBerry|Multiscale|ExtremeSpeed,IceSpinner,TeraBlast,Protect|Adamant|252,116,,,,140||||50|]" +
  "Grimmsnarl||LightClay|Prankster|Reflect,LightScreen,SpiritBreak,ThunderWave|Careful|252,4,,,252,||||50|]" +
  "Garchomp||LifeOrb|RoughSkin|Earthquake,DragonClaw,RockSlide,Protect|Jolly|4,252,,,,252||||50|";

export const FORMATS: Record<FormatId, FormatDef> = {
  gen9randombattle: {
    id: "gen9randombattle",
    label: "Gen 9 Random Battle",
    gametype: "singles",
    teamPreview: false,
    teamSize: 6,
  },
  gen9vgc2025regi: {
    id: "gen9vgc2025regi",
    label: "VGC 2025 Reg I",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [VGC_TEAM_A, VGC_TEAM_B],
  },
};

export const FORMAT_LIST: FormatDef[] = [FORMATS.gen9randombattle, FORMATS.gen9vgc2025regi];
