// The formats the Battle tab offers. Each entry maps a UI button to an engine
// format id (the actual @pkmn/sim format that runs the battle).
//
// - gen9randombattle: singles, teams auto-generated by @pkmn/randoms.
// - VGC 2025 Reg I: doubles + team preview, allows up to two Restricted Legendaries.
// - VGC 2026 Reg M-B: its own ruleset, built from Reg I by hard-banning the whole
//   Restricted Legendary class (and dropping the "up to two" allowance) — Mythicals
//   are already banned by Flat Rules. That reproduces Reg M-B's real structure on the
//   Gen 9 engine: Lv 50 doubles, Open Team Sheets, Species/Item/Nickname clauses,
//   bring 6 pick 4. What it can't reproduce is Mega Evolution and the Champions-only
//   Pokémon (Reg M-B is a Pokémon Champions format; that data isn't in @pkmn/sim) —
//   the UI note says so. VGC has no team generator, so each format ships legal,
//   pre-validated sample teams (checked with the real TeamValidator).

export type FormatKey = "gen9randombattle" | "vgcregi" | "vgcregmb";

export interface FormatDef {
  key: FormatKey;
  label: string;
  engineFormat: string; // actual @pkmn/sim format id passed to the simulator
  gametype: "singles" | "doubles";
  teamPreview: boolean;
  teamSize: number; // how many are brought to the field (pick N)
  packedTeams?: string[]; // when set, teams come from here instead of the generator
  note?: string; // small clarifying caption under the picker
}

// --- Legal VGC teams (level 50, no Restricted Legendaries or Mythicals). ---
// Verified with the real TeamValidator: Reg I teams pass gen9vgc2025regi, and the
// Reg M-B teams pass the stricter Reg-M-B ruleset below (no problems).

const REGI_A =
  "Incineroar||SafetyGoggles|Intimidate|FakeOut,KnockOff,FlareBlitz,PartingShot|Adamant|244,4,4,,20,236||||50|]" +
  "Rillaboom||AssaultVest|GrassySurge|FakeOut,GrassyGlide,WoodHammer,Uturn|Adamant|252,116,,,140,||||50|]" +
  "Flutter Mane||FocusSash|Protosynthesis|Moonblast,ShadowBall,DazzlingGleam,Protect|Timid|,,4,252,,252||||50|]" +
  "Landorus-Therian||LifeOrb|Intimidate|Earthquake,RockSlide,Uturn,Protect|Jolly|4,252,,,,252||||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Calm|236,,172,,100,||||50|]" +
  "Urshifu-Rapid-Strike||MysticWater|UnseenFist|SurgingStrikes,CloseCombat,AquaJet,Protect|Adamant|4,252,,,,252||||50|";

const REGI_B =
  "Gholdengo||ChoiceScarf|GoodasGold|MakeItRain,ShadowBall,Thunderbolt,Trick|Timid|,,4,252,,252||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|100,252,,,156,||||50|]" +
  "Chi-Yu||ChoiceSpecs|BeadsofRuin|HeatWave,DarkPulse,Overheat,Snarl|Modest|,,4,252,,252||||50|]" +
  "Dragonite||SitrusBerry|Multiscale|ExtremeSpeed,IceSpinner,TeraBlast,Protect|Adamant|252,116,,,,140||||50|]" +
  "Grimmsnarl||LightClay|Prankster|Reflect,LightScreen,SpiritBreak,ThunderWave|Careful|252,4,,,252,||||50|]" +
  "Garchomp||LifeOrb|RoughSkin|Earthquake,DragonClaw,RockSlide,Protect|Jolly|4,252,,,,252||||50|";

// Distinct pool for the Reg M-B button. Champions training: 66 EV points per Pokémon (max 32
// in a single stat), each worth +1 to that stat (see engineFormat "EV Limit = 66" +
// champions-stats.ts). Spreads put 32 into each of two key stats (64 total), matching the
// minus-Speed / offensive natures.
const REGMB_C =
  "Torkoal||Charcoal|Drought|Eruption,HeatWave,EarthPower,Protect|Quiet|32,,,32,,||,,,,,0||50|]" +
  "Hatterene||LifeOrb|MagicBounce|ExpandingForce,DazzlingGleam,MysticalFire,TrickRoom|Quiet|32,,,32,,||,,,,,0||50|]" +
  "Indeedee-F||PsychicSeed|PsychicSurge|FollowMe,TrickRoom,DazzlingGleam,HelpingHand|Sassy|32,,,,32,||,,,,,0||50|]" +
  "Ursaluna||FlameOrb|Guts|Facade,HeadlongRush,Crunch,Protect|Brave|32,32,,,,||,,,,,0||50|]" +
  "Kingambit||AssaultVest|Defiant|KowtowCleave,SuckerPunch,IronHead,LowKick|Brave|32,32,,,,||,,,,,0||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Sassy|32,,,,32,||,,,,,0||50|";

const REGMB_D =
  "Tornadus||FocusSash|Prankster|BleakwindStorm,Tailwind,Taunt,Protect|Timid|,,,32,,32||||50|]" +
  "Archaludon||PowerHerb|Stamina|ElectroShot,FlashCannon,DracoMeteor,BodyPress|Modest|32,,,32,,||||50|]" +
  "Ursaluna-Bloodmoon||LifeOrb|MindsEye|BloodMoon,EarthPower,HyperVoice,Protect|Modest|32,,,32,,||,,,,,0||50|]" +
  "Rillaboom||MiracleSeed|GrassySurge|GrassyGlide,FakeOut,HighHorsepower,Protect|Adamant|,32,,,,32||||50|]" +
  "Flutter Mane||BoosterEnergy|Protosynthesis|Moonblast,ShadowBall,IcyWind,Protect|Timid|,,,32,,32||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|32,32,,,,||||50|";

export const FORMATS: Record<FormatKey, FormatDef> = {
  gen9randombattle: {
    key: "gen9randombattle",
    label: "Gen 9 Random Battle",
    engineFormat: "gen9randombattle",
    gametype: "singles",
    teamPreview: false,
    teamSize: 6,
  },
  vgcregi: {
    key: "vgcregi",
    label: "VGC 2025 Reg I",
    engineFormat: "gen9vgc2025regi",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [REGI_A, REGI_B],
  },
  vgcregmb: {
    key: "vgcregmb",
    label: "VGC 2026 Reg M-B",
    // Reg I + hard ban on all Restricted Legendaries (Reg I allowed two). No space
    // after the comma: the battle engine splits @@@ rules on "," without trimming.
    engineFormat: "gen9vgc2025regi@@@!Limit Two Restricted,-Restricted Legendary,!EV Limit,EV Limit = 66",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [REGMB_C, REGMB_D],
    note: "Real Reg M-B ruleset: Lv 50 doubles, Open Team Sheets, no Mythicals or Restricted Legendaries, bring 6 pick 4. Champions training — 66 EV points per Pokémon (max 32 in one stat), each adds +1 to that stat (IVs unused). Mega Evolution and Champions-only Pokémon aren't in the in-browser Gen 9 engine, so those are unavailable.",
  },
};

export const FORMAT_LIST: FormatDef[] = [FORMATS.gen9randombattle, FORMATS.vgcregi, FORMATS.vgcregmb];
